services:
  - type: web
    name: junkhop-backend
    env: php
    runtime: php-8.2
    buildCommand: |
      # Install PHP dependencies
      composer install --no-interaction --prefer-dist --optimize-autoloader
      
      # Install Node.js dependencies
      npm install
      npm run build
      
      # Clear Laravel caches and prepare for production
      php artisan config:clear
      php artisan route:clear
      php artisan view:clear
      php artisan storage:link
      php artisan migrate --force
    startCommand: php artisan octane:start --server=roadrunner --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        fromDatabase:
          name: junkhop-db
          property: connectionString
      - key: APP_URL
        value: https://junkhop-backend.onrender.com
      - key: FRONTEND_URL
        value: https://junkhop.vercel.app
      - key: SESSION_DOMAIN
        value: onrender.com
      - key: SANCTUM_STATEFUL_DOMAINS
        value: junkhop.vercel.app
      - key: APP_KEY
        generateValue: true
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: NODE_VERSION
        value: 20
databases:
  - name: junkhop-db
    plan: free
